# -*- coding: utf-8 -*-
"""agentic_ai_assistant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yGNbCQk5zwM7ZMZTPI8BjEYgV8waf3P_

# 🤖 Agentic AI Assistant — LangChain + LangGraph

**Use Case:** Multi-Tool Research & Productivity Assistant  
**Tools:** Wikipedia Search, Weather (wttr.in), Calculator, Joke API  
**Memory:** LangGraph MemorySaver checkpointing  
**UI:** Gradio Chat Interface

## Install Dependencies
"""

!pip install langchain langgraph langchain-groq gradio wikipedia requests -q

"""## Imports & API Key Setup"""

import os
import json
import math
import requests
import wikipedia
from typing import Annotated, TypedDict

from langchain_groq import ChatGroq
from langchain_core.tools import tool
from langchain_core.messages import HumanMessage, AIMessage, SystemMessage

from langgraph.graph import StateGraph, END
from langgraph.graph.message import add_messages
from langgraph.prebuilt import ToolNode
from langgraph.checkpoint.memory import MemorySaver

import gradio as gr

try:
    from google.colab import userdata
    GROQ_API_KEY = userdata.get("groq")
    print("✅ Loaded API key from Colab Secrets")
except Exception:
    GROQ_API_KEY = os.environ.get("GROQ_API_KEY", "")
    if GROQ_API_KEY:
        print("✅ Loaded API key from environment variable")
    else:
        raise ValueError("❌ No API key found. Add a Colab secret named 'groq'.")

os.environ["GROQ_API_KEY"] = GROQ_API_KEY
# ───────────────────────────────────────────────────────────────────────────────

print("✅ Imports complete!")

"""## Defining Tools

We define **4 tools**:
1. `wikipedia_search` — External API (Wikipedia)
2. `get_weather` — External API (wttr.in, no key needed)
3. `get_joke` — External API (Official Joke API)
4. `calculator` — Custom Python tool
"""

# ── Tool 1: Wikipedia Search (External API) ────────────────────────────────────
@tool
def wikipedia_search(query: str) -> str:
    """Search Wikipedia for information about any topic. Use this for factual questions about people, places, history, science, etc."""
    try:
        wikipedia.set_lang("en")
        result = wikipedia.summary(query, sentences=4, auto_suggest=True)
        return f"Wikipedia result for '{query}':\n{result}"
    except wikipedia.exceptions.DisambiguationError as e:
        # Try the first suggestion
        try:
            result = wikipedia.summary(e.options[0], sentences=4)
            return f"Wikipedia result for '{e.options[0]}':\n{result}"
        except Exception:
            return f"Multiple results found for '{query}'. Please be more specific. Options: {', '.join(e.options[:5])}"
    except wikipedia.exceptions.PageError:
        return f"No Wikipedia page found for '{query}'. Try a different search term."
    except Exception as e:
        return f"Wikipedia search error: {str(e)}"


# ── Tool 2: Weather (External API — wttr.in, completely free, no key needed) ───
@tool
def get_weather(city: str) -> str:
    """Get current weather for any city. Use this when the user asks about weather conditions."""
    try:
        url = f"https://wttr.in/{city}?format=j1"
        headers = {"User-Agent": "Mozilla/5.0"}
        response = requests.get(url, headers=headers, timeout=10)
        data = response.json()

        current = data["current_condition"][0]
        area = data["nearest_area"][0]
        area_name = area["areaName"][0]["value"]
        country = area["country"][0]["value"]

        temp_c = current["temp_C"]
        feels_like = current["FeelsLikeC"]
        humidity = current["humidity"]
        desc = current["weatherDesc"][0]["value"]
        wind_kmph = current["windspeedKmph"]
        visibility = current["visibility"]

        return (
            f"🌤 Weather in {area_name}, {country}:\n"
            f"  Condition: {desc}\n"
            f"  Temperature: {temp_c}°C (Feels like {feels_like}°C)\n"
            f"  Humidity: {humidity}%\n"
            f"  Wind Speed: {wind_kmph} km/h\n"
            f"  Visibility: {visibility} km"
        )
    except Exception as e:
        return f"Could not retrieve weather for '{city}': {str(e)}"


# ── Tool 3: Joke API (External API — Official Joke API, free, no key) ──────────
@tool
def get_joke(category: str = "general") -> str:
    """Fetch a random joke. Categories: general, programming, knock-knock. Use when the user wants a joke or some humor."""
    try:
        valid_categories = ["general", "programming", "knock-knock"]
        cat = category.lower() if category.lower() in valid_categories else "general"
        url = f"https://official-joke-api.appspot.com/jokes/{cat}/random"
        response = requests.get(url, timeout=10)
        jokes = response.json()
        if isinstance(jokes, list):
            joke = jokes[0]
        else:
            joke = jokes
        return f"😄 {joke['setup']}\n\n👉 {joke['punchline']}"
    except Exception as e:
        return f"Could not fetch a joke: {str(e)}"


# ── Tool 4: Calculator (Custom Python Tool) ────────────────────────────────────
@tool
def calculator(expression: str) -> str:
    """
    Evaluate mathematical expressions safely. Supports: +, -, *, /, **, sqrt(), sin(), cos(), tan(), log(), pi, e.
    Examples: '2 + 2', 'sqrt(144)', '3**4', 'log(100)', 'pi * 5**2'
    """
    try:
        # Safe namespace with math functions
        safe_namespace = {
            "__builtins__": {},
            "sqrt": math.sqrt,
            "sin": math.sin,
            "cos": math.cos,
            "tan": math.tan,
            "log": math.log10,
            "ln": math.log,
            "abs": abs,
            "round": round,
            "pi": math.pi,
            "e": math.e,
            "pow": pow,
            "floor": math.floor,
            "ceil": math.ceil,
        }
        result = eval(expression, safe_namespace)
        return f"🧮 {expression} = {result}"
    except ZeroDivisionError:
        return "Error: Division by zero is undefined."
    except Exception as e:
        return f"Calculator error: {str(e)}. Make sure to use valid math syntax."


# Bundle all tools
tools = [wikipedia_search, get_weather, get_joke, calculator]
print(f"✅ {len(tools)} tools defined: {[t.name for t in tools]}")

"""## Set Up LLM (Groq)"""

# Initialize Groq LLM (free tier available)
llm = ChatGroq(
    model="llama-3.3-70b-versatile",   # Fast, free, capable model on Groq
    temperature=0.7,
    max_tokens=1024,
)

# Bind tools to the LLM so it can call them
llm_with_tools = llm.bind_tools(tools)

print("✅ LLM initialized with tools bound!")
print(f"   Model: llama3-8b-8192 via Groq")

"""## Defining LangGraph State & Workflow

### Workflow Architecture
```
User Input
    │
    ▼
[agent_node]  ← LLM decides: respond directly OR call a tool
    │
    ├── tool_calls present? ──YES──► [tool_node] ──► back to [agent_node]
    │
    └── No tools needed? ─────────► END (final response)
```
"""

# ── Graph State ────────────────────────────────────────────────────────────────
class AgentState(TypedDict):
    """State holds the full conversation message history."""
    messages: Annotated[list, add_messages]


# ── System Prompt ──────────────────────────────────────────────────────────────
SYSTEM_PROMPT = """You are a helpful, friendly AI assistant with access to the following tools:

1. wikipedia_search — Search Wikipedia for factual information on any topic
2. get_weather — Get live weather for any city
3. get_joke — Fetch a random joke (categories: general, programming, knock-knock)
4. calculator — Evaluate math expressions safely

Guidelines:
- Always use tools when the user asks for information you can look up
- For weather questions, extract the city name and call get_weather
- For math questions, always use the calculator tool
- For factual questions, use wikipedia_search
- Be concise, friendly, and helpful
- Always explain what tool you used and summarize results clearly
"""


# ── Agent Node ─────────────────────────────────────────────────────────────────
def agent_node(state: AgentState) -> AgentState:
    """Main agent node: calls LLM with tools."""
    messages = state["messages"]

    # Prepend system prompt if not already there
    if not messages or not isinstance(messages[0], SystemMessage):
        messages = [SystemMessage(content=SYSTEM_PROMPT)] + list(messages)

    response = llm_with_tools.invoke(messages)
    return {"messages": [response]}


# ── Conditional Routing ────────────────────────────────────────────────────────
def should_use_tools(state: AgentState) -> str:
    """Route to tools if the LLM requested tool calls, otherwise end."""
    last_message = state["messages"][-1]
    if hasattr(last_message, "tool_calls") and last_message.tool_calls:
        return "use_tools"
    return "end"


# ── Build Graph ────────────────────────────────────────────────────────────────
tool_node = ToolNode(tools)  # Pre-built node that executes tools
memory = MemorySaver()        # In-memory checkpointer for conversation history

graph_builder = StateGraph(AgentState)

# Add nodes
graph_builder.add_node("agent", agent_node)
graph_builder.add_node("tools", tool_node)

# Set entry point
graph_builder.set_entry_point("agent")

# Conditional edge: after agent, decide to use tools or end
graph_builder.add_conditional_edges(
    "agent",
    should_use_tools,
    {"use_tools": "tools", "end": END}
)

# After tools execute, return to agent for final response
graph_builder.add_edge("tools", "agent")

# Compile with memory checkpointing
graph = graph_builder.compile(checkpointer=memory)

print("✅ LangGraph workflow compiled with memory checkpointing!")

"""## Visualizing the Graph



"""

# Try to display the graph structure
try:
    from IPython.display import Image, display
    display(Image(graph.get_graph().draw_mermaid_png()))
except Exception:
    # If graphviz not installed, print the mermaid diagram instead
    print(graph.get_graph().draw_mermaid())

"""## Test the Agent (CLI)"""

def chat(user_message: str, thread_id: str = "test-thread") -> str:
    """Send a message to the agent and return the response."""
    config = {"configurable": {"thread_id": thread_id}}
    result = graph.invoke(
        {"messages": [HumanMessage(content=user_message)]},
        config=config
    )
    # Get the last AI message
    ai_messages = [m for m in result["messages"] if isinstance(m, AIMessage)]
    return ai_messages[-1].content if ai_messages else "No response generated."


# ── Quick Tests ────────────────────────────────────────────────────────────────
print("=" * 60)
print("TEST 1: Calculator")
print("=" * 60)
response = chat("What is sqrt(256) + 3^4?")
print(f"Agent: {response}\n")

print("=" * 60)
print("TEST 2: Wikipedia")
print("=" * 60)
response = chat("Tell me about the Eiffel Tower")
print(f"Agent: {response}\n")

print("=" * 60)
print("TEST 3: Weather")
print("=" * 60)
response = chat("What's the weather in London?")
print(f"Agent: {response}\n")

"""## Multi-Turn Memory Test"""

# Test conversation memory — same thread_id = same conversation context
THREAD = "memory-test-001"

print("🧠 MEMORY TEST — Multi-turn conversation")
print("=" * 60)

# Turn 1
r1 = chat("Hi! My name is Ahmed.", thread_id=THREAD)
print(f"Turn 1 — User: Hi! My name is Ahmed.")
print(f"Turn 1 — Agent: {r1}\n")

# Turn 2
r2 = chat("What is 15 * 24?", thread_id=THREAD)
print(f"Turn 2 — User: What is 15 * 24?")
print(f"Turn 2 — Agent: {r2}\n")

# Turn 3 — Tests if agent remembers the name
r3 = chat("Do you remember my name?", thread_id=THREAD)
print(f"Turn 3 — User: Do you remember my name?")
print(f"Turn 3 — Agent: {r3}\n")

print("✅ Memory is working — the agent remembered context across turns!")

"""## Gradio Interface"""

import uuid

# Each Gradio session gets a unique thread ID for isolated memory
def create_gradio_interface():

    def respond(message, history, session_id):
        """Process user message and return AI response."""
        if not session_id:
            session_id = str(uuid.uuid4())

        try:
            config = {"configurable": {"thread_id": session_id}}
            result = graph.invoke(
                {"messages": [HumanMessage(content=message)]},
                config=config
            )
            ai_messages = [m for m in result["messages"] if isinstance(m, AIMessage)]
            response = ai_messages[-1].content if ai_messages else "I couldn't generate a response."
        except Exception as e:
            response = f"❌ Error: {str(e)}\n\nPlease check your GROQ_API_KEY."

        return response

    def new_session():
        """Generate a new session ID to reset memory."""
        return str(uuid.uuid4()), []

    # ── Gradio UI ──────────────────────────────────────────────────────────────
    with gr.Blocks(
        title="🤖 Agentic AI Assistant",
        theme=gr.themes.Soft(primary_hue="blue", secondary_hue="slate"),
        css="""
            .header { text-align: center; padding: 20px; }
            .tool-badge {
                display: inline-block;
                background: #e8f4fd;
                border: 1px solid #bee3f8;
                border-radius: 12px;
                padding: 4px 12px;
                margin: 4px;
                font-size: 13px;
                color: #2b6cb0;
            }
        """
    ) as demo:

        # ── Header ─────────────────────────────────────────────────────────────
        gr.HTML("""
        <div class="header">
            <h1>🤖 Agentic AI Research Assistant</h1>
            <p style="color: #666; font-size: 15px;">Powered by LangChain + LangGraph + Groq (LLaMA 3)</p>
            <div>
                <span class="tool-badge">📚 Wikipedia Search</span>
                <span class="tool-badge">🌤 Live Weather</span>
                <span class="tool-badge">🧮 Calculator</span>
                <span class="tool-badge">😄 Joke Generator</span>
            </div>
        </div>
        """)

        # ── State ──────────────────────────────────────────────────────────────
        session_id = gr.State(value=str(uuid.uuid4()))

        # ── Chat Interface ─────────────────────────────────────────────────────
        with gr.Row():
            with gr.Column(scale=3):
                chatbot = gr.Chatbot(
                    label="Conversation",
                    height=480,
                    show_label=True,
                    avatar_images=(None, "https://api.dicebear.com/7.x/bottts/svg?seed=agent"),
                    bubble_full_width=False,
                )
                with gr.Row():
                    msg_input = gr.Textbox(
                        placeholder="Ask me anything... (weather, facts, math, jokes)",
                        label="Your Message",
                        scale=4,
                        lines=1,
                    )
                    send_btn = gr.Button("Send 🚀", variant="primary", scale=1)

            with gr.Column(scale=1):
                gr.Markdown("### 🎯 Try these prompts")

                example_prompts = [
                    "What's the weather in Tokyo?",
                    "Tell me about Albert Einstein",
                    "Calculate sqrt(1764) + 15*8",
                    "Tell me a programming joke",
                    "What is the capital of Australia?",
                    "What is 2^10 divided by 8?",
                    "Tell me about black holes",
                    "Weather in Karachi",
                ]

                for prompt in example_prompts:
                    gr.Button(prompt, size="sm").click(
                        fn=lambda p=prompt: p,
                        outputs=msg_input
                    )

                gr.Markdown("---")
                new_chat_btn = gr.Button("🔄 New Conversation", variant="secondary")
                gr.Markdown(
                    "*Each session has its own memory. Click 'New Conversation' to start fresh.*",
                    elem_classes=["hint"]
                )

        # ── Info Accordion ─────────────────────────────────────────────────────
        with gr.Accordion("📖 About this Application", open=False):
            gr.Markdown("""
            ## Architecture
            This app uses a **LangGraph ReAct-style agentic workflow**:

            ```
            User Input → [Agent Node] → decides → [Tool Node] → back to [Agent Node] → Response
            ```

            - **LangGraph** manages the stateful workflow with conditional routing
            - **MemorySaver** checkpoints keep conversation history per session
            - **Groq** provides fast, free inference with LLaMA 3
            - **Tools** are called automatically based on user intent

            ## Memory
            - Each conversation has a unique `thread_id`
            - LangGraph's `MemorySaver` persists message history across turns
            - Click **New Conversation** to start a fresh session
            """)

        # ── Event Handlers ─────────────────────────────────────────────────────
        def user_submit(message, history, sid):
            if not message.strip():
                return history, "", sid
            ai_response = respond(message, history, sid)
            history = history + [[message, ai_response]]
            return history, "", sid

        send_btn.click(
            fn=user_submit,
            inputs=[msg_input, chatbot, session_id],
            outputs=[chatbot, msg_input, session_id]
        )
        msg_input.submit(
            fn=user_submit,
            inputs=[msg_input, chatbot, session_id],
            outputs=[chatbot, msg_input, session_id]
        )
        new_chat_btn.click(
            fn=new_session,
            outputs=[session_id, chatbot]
        )

    return demo


print("✅ Gradio interface defined!")

"""## Launching the Application"""

demo = create_gradio_interface()
demo.launch(
    share=True,          # Creates a public link (useful for demo/screenshots)
    debug=False,
    show_error=True,
)

"""---
## 📊 Workflow Diagram

```
┌─────────────────────────────────────────────────────────────────┐
│                    AGENTIC AI SYSTEM                            │
│                                                                 │
│  ┌──────────┐    ┌──────────────────────────────────────────┐   │
│  │  GRADIO  │    │         LANGGRAPH WORKFLOW               │   │
│  │    UI    │───►│                                          │   │
│  │          │    │   ┌────────────┐   tool_calls?           │   │
│  │  Chat    │    │   │            │ ────YES────►  ┌──────┐  │   │
│  │  Input   │    │   │  AGENT     │               │TOOLS │  │   │
│  │          │    │   │  NODE      │ ◄─────────── │ NODE │  │   │
│  │  Message │◄───│   │  (LLaMA3)  │               └──────┘  │   │
│  │  History │    │   │            │ ────NO─────►  END        │   │
│  └──────────┘    │   └────────────┘                          │   │
│                  └──────────────────────────────────────────┘   │
│                                                                 │
│  TOOLS:                         MEMORY:                        │
│  ┌─────────────────────┐        ┌──────────────────────────┐   │
│  │ 📚 Wikipedia Search │        │  MemorySaver             │   │
│  │ 🌤 wttr.in Weather  │        │  thread_id per session   │   │
│  │ 😄 Joke API         │        │  persists across turns   │   │
│  │ 🧮 Calculator       │        └──────────────────────────┘   │
│  └─────────────────────┘                                       │
└─────────────────────────────────────────────────────────────────┘
```


"""